import { ISeatMapData } from "@/types/SeatMapData.types"

export const SeatMapData = {
  planeMap: {
    cabinType: "Business",
    seatMapRow: [
      {
        rowNumber: "0",
        cabinElement: [
          {
            rowNumber: "0",
            type: "TOILET",
            elementString: null,
            seatLocationType: "TOILET",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: true,
          },
          {
            rowNumber: "0",
            type: "MEAL",
            elementString: null,
            seatLocationType: "TOILET",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: true,
          },
          {
            rowNumber: "0",
            type: "TOILET",
            elementString: null,
            seatLocationType: "TOILET",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: true,
          },
        ],
      },
      {
        rowNumber: "0",
        cabinElement: [
          {
            rowNumber: null,
            type: "DOOR",
            elementString: null,
            seatLocationType: "DOOR",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: null,
            type: "EXITCORRIDOR",
            elementString: null,
            seatLocationType: "EXITCORRIDOR",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: null,
            type: "DOOR",
            elementString: null,
            seatLocationType: "DOOR",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
        ],
      },
      {
        rowNumber: "1",
        cabinElement: [
          {
            rowNumber: null,
            type: "WINDOW",
            elementString: null,
            seatLocationType: "WINDOW",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "1",
            type: "SEAT",
            planeSeat: {
              seatNumber: "01A",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: true,
              aisle: false,
              window: true,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: false,
              reserved: true,
              seatType: "WINDOW",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "FARE",
                  currency: "EUR",
                  code: "Non-Chargable Seat",
                  amount: 6000,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: true,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "1",
            type: "SEAT",
            planeSeat: {
              seatNumber: "01C",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: true,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: true,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: true,
              seatType: "CORRIDOR",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "NO FARE",
                  currency: "EUR",
                  code: "Non-Chargable Seat",
                  amount: 400,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: true,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "1",
            type: "CORRIDOR",
            planeSeat: {
              seatNumber: null,
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: true,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "CORRIDOR",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: "CORRIDOR",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "1",
            type: "SEAT",
            planeSeat: {
              seatNumber: "01D",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: true,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: true,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: true,
              seatType: "CORRIDOR",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "NO FARE",
                  currency: null,
                  code: "Non-Chargable Seat",
                  amount: null,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: true,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "1",
            type: "SEAT",
            planeSeat: {
              seatNumber: "01F",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: true,
              aisle: false,
              window: true,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: false,
              reserved: true,
              seatType: "WINDOW",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "FARE",
                  currency: "EUR",
                  code: "Non-Chargable Seat",
                  amount: 6000,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: true,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: null,
            type: "WINDOW",
            planeSeat: {
              seatNumber: null,
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: false,
              reserved: false,
              seatType: null,
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: null,
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: "WINDOW",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
        ],
      },
      {
        rowNumber: "2",
        cabinElement: [
          {
            rowNumber: null,
            type: "WINDOW",
            planeSeat: {
              seatNumber: null,
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: false,
              reserved: false,
              seatType: null,
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: null,
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: "WINDOW",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "2",
            type: "SEAT",
            planeSeat: {
              seatNumber: "02A",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: true,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "WINDOW",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "FARE",
                  currency: "EUR",
                  code: "Non-Chargable Seat",
                  amount: 6000,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "2",
            type: "SEAT",
            planeSeat: {
              seatNumber: "02C",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: true,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: true,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "CORRIDOR",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "NO FARE",
                  currency: null,
                  code: "Non-Chargable Seat",
                  amount: null,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "2",
            type: "CORRIDOR",
            planeSeat: {
              seatNumber: null,
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: true,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "CORRIDOR",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: "CORRIDOR",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "2",
            type: "SEAT",
            planeSeat: {
              seatNumber: "02D",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: true,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: true,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "CORRIDOR",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "NO FARE",
                  currency: null,
                  code: "Non-Chargable Seat",
                  amount: null,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "2",
            type: "SEAT",
            planeSeat: {
              seatNumber: "02F",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: true,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "WINDOW",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "FARE",
                  currency: "EUR",
                  code: "Non-Chargable Seat",
                  amount: 6000,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: null,
            type: "WINDOW",
            planeSeat: {
              seatNumber: null,
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: false,
              reserved: false,
              seatType: null,
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: null,
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: "WINDOW",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
        ],
      },
      {
        rowNumber: "3",
        cabinElement: [
          {
            rowNumber: null,
            type: "WINDOW",
            planeSeat: {
              seatNumber: null,
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: false,
              reserved: false,
              seatType: null,
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: null,
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: "WINDOW",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "3",
            type: "SEAT",
            planeSeat: {
              seatNumber: "03A",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: true,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "WINDOW",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "FARE",
                  currency: "EUR",
                  code: "Non-Chargable Seat",
                  amount: 6000,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "3",
            type: "SEAT",
            planeSeat: {
              seatNumber: "03C",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: true,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: true,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "CORRIDOR",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "NO FARE",
                  currency: null,
                  code: "Non-Chargable Seat",
                  amount: null,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "3",
            type: "CORRIDOR",
            planeSeat: {
              seatNumber: null,
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: true,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "CORRIDOR",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: "CORRIDOR",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "3",
            type: "SEAT",
            planeSeat: {
              seatNumber: "03D",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: true,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: true,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "CORRIDOR",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "NO FARE",
                  currency: null,
                  code: "Non-Chargable Seat",
                  amount: null,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "3",
            type: "SEAT",
            planeSeat: {
              seatNumber: "03F",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: true,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "WINDOW",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "FARE",
                  currency: "EUR",
                  code: "Non-Chargable Seat",
                  amount: 6000,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: null,
            type: "WINDOW",
            planeSeat: {
              seatNumber: null,
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: false,
              reserved: false,
              seatType: null,
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: null,
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: "WINDOW",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
        ],
      },
      {
        rowNumber: "4",
        cabinElement: [
          {
            rowNumber: null,
            type: "WINDOW",
            planeSeat: {
              seatNumber: null,
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: false,
              reserved: false,
              seatType: null,
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: null,
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: "WINDOW",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "4",
            type: "SEAT",
            planeSeat: {
              seatNumber: "04A",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: true,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "WINDOW",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "FARE",
                  currency: "EUR",
                  code: "Non-Chargable Seat",
                  amount: 6000,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "4",
            type: "SEAT",
            planeSeat: {
              seatNumber: "04C",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: true,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: true,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "CORRIDOR",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "NO FARE",
                  currency: null,
                  code: "Non-Chargable Seat",
                  amount: null,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "4",
            type: "CORRIDOR",
            planeSeat: {
              seatNumber: null,
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: true,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "CORRIDOR",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: "CORRIDOR",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "4",
            type: "SEAT",
            planeSeat: {
              seatNumber: "04D",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: true,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: true,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "CORRIDOR",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "FARE",
                  currency: "TRY",
                  code: "Non-Chargable Seat",
                  amount: 1900,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "4",
            type: "SEAT",
            planeSeat: {
              seatNumber: "04F",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: true,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "WINDOW",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "FARE",
                  currency: "EUR",
                  code: "Non-Chargable Seat",
                  amount: 6000,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: null,
            type: "WINDOW",
            planeSeat: {
              seatNumber: null,
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: false,
              reserved: false,
              seatType: null,
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: null,
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: "WINDOW",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
        ],
      },
      {
        rowNumber: "5",
        cabinElement: [
          {
            rowNumber: null,
            type: "WINDOW",
            planeSeat: {
              seatNumber: null,
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: false,
              reserved: false,
              seatType: null,
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: null,
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: "WINDOW",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "5",
            type: "SEAT",
            planeSeat: {
              seatNumber: "05A",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: true,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "WINDOW",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "FARE",
                  currency: "EUR",
                  code: "Non-Chargable Seat",
                  amount: 6000,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "5",
            type: "SEAT",
            planeSeat: {
              seatNumber: "05C",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: true,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: true,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "CORRIDOR",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "NO FARE",
                  currency: null,
                  code: "Non-Chargable Seat",
                  amount: null,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "5",
            type: "CORRIDOR",
            planeSeat: {
              seatNumber: null,
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: true,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "CORRIDOR",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: "CORRIDOR",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "5",
            type: "SEAT",
            planeSeat: {
              seatNumber: "05D",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: true,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: true,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "CORRIDOR",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "NO FARE",
                  currency: null,
                  code: "Non-Chargable Seat",
                  amount: null,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: "5",
            type: "SEAT",
            planeSeat: {
              seatNumber: "05F",
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: true,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: true,
              reserved: false,
              seatType: "WINDOW",
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: [
                {
                  description: "FARE",
                  currency: "EUR",
                  code: "Non-Chargable Seat",
                  amount: 6000,
                  mileAmount: null,
                  mileCurrency: null,
                  passengerRph: "1",
                  premiumCode: "1",
                  feeCode: null,
                  canSelectSeat: true,
                  mandatoryInd: null,
                  beforeDiscountAmount: null,
                  beforeDiscountMileAmount: null,
                },
              ],
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: null,
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
          {
            rowNumber: null,
            type: "WINDOW",
            planeSeat: {
              seatNumber: null,
              nonSmoking: false,
              smoking: false,
              exit: false,
              basinet: false,
              aisle: false,
              window: false,
              center: false,
              notForMedical: false,
              notForYoung: false,
              notForInfant: false,
              notForChild: false,
              notForPetc: false,
              forTransit: false,
              largeSpace: false,
              chargableSeat: false,
              leastPreferable: false,
              handicap: false,
              selectable: false,
              available: false,
              standard: false,
              reserved: false,
              seatType: null,
              rightSideExtraSeatAvailable: false,
              leftSideExtraSeatAvailable: false,
              leftSideExtraSeatNumber: null,
              rightSideExtraSeatNumber: null,
              planeSeatAmenity: null,
              planeSeatAmenities: null,
              mandatoryInd: null,
              planeSection: null,
              premiumCode: null,
              occupied: false,
            },
            elementString: null,
            seatLocationType: "WINDOW",
            wcFlag: false,
            exitCorridor: false,
            wcSeatFlag: false,
          },
        ],
      },
    ],
    seatLetters: ["A", "C", "", "D", "F"],
  },
} satisfies ISeatMapData
